### ISSUE TITLE
locationTimeType

### ISSUE THREAD

**Issue by tormodv** [ebu/ccdm#119]
:LocationTimeType <http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#LocationTimeType>
:locationTimeType <http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#locationTimeType>

Do we need this, is it the same as the timezone?

**Comment by JuergenGrupp** [comment]
I can't see any use in this property and propose to remove it.
