### ISSUE TITLE
Version or derivied?

### ISSUE THREAD

**Issue by tormodv** [ebu/ccdm#133]
:derivedTo <http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#derivedTo>
:isDerivedFrom <http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#isDerivedFrom>
ebuccdm:isDerivedFrom <http://www.ebu.ch/metadata/ontologies/ebuccdm#isDerivedFrom>

Do we need them?

:isVersionOf <http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#isVersionOf>
:hasVersion <http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#hasVersion>

Is the two latter one good enough for the version relationship between BO?

**Comment by JuergenGrupp** [comment]
I think we need both. A BO2 being "derived from" a BO1, may look totally different, with different story. However, being "a version of" implies different editing decisions but the same story.
We do not need the ebuccdm:isDerivedFrom as we have that in ebucore already.

**Comment by tormodv** [comment]
Then we delete ebuccdm:isDerivedFrom and put the rest on thenBO
