### ISSUE TITLE
Subclass structure of EditorialObject

### ISSUE THREAD

**Issue by JuergenGrupp** [ebu/ccdm#176]
The subclass structure of EditorialObject is currently not distinguishing between works and segments. Only groups are explicitly modelled, not as subclasses of EditorialObject, but as a sibling. Furthermore, a Brand is also modelled as a Group, which imho is not the best way to do it. Current situation is:
![image](https://user-images.githubusercontent.com/80782611/185965317-67622103-1083-496d-90e7-bcb27ac4f723.png)

Proposal: Explicitly distinguish EditorialObjects that represent works ("work" in the same sense like a "piece of art"), groups of works and segments of works ("segment" in the sense of a "fragment of a piece of art") with the subclasses "EditorialWork", "EditorialGroup" and "EditorialSegment". This allows to also explicitly distinguish a set of simple object properties pointing inbetween the 3 layers ("hasEditorialGroup", "hasEditorialWork" and "hasParentEditorialSegment"). Another subclass refinement can then lead to the following hierarchy of subclasses of EditorialObject:

-    EditorialGroup
 --       Motto
 --       Series
 --       Serial
 --       Season
-    EditorialWork
 --       Programme
 --       fims:BMContent
 --       Episode
 --       Article
 --       Post
-    EditorialSegment
 --       Item
 --       Clip
 --       Scene
 --       Shot
 --       Take

Every object property between these classes can also be a subproperty of one of "hasEditorialGroup", "hasEditorialWork" and "hasParentEditorialSegment". This will be helpful for future use of inference and to simplify SPARQL-Queries.
![image](https://user-images.githubusercontent.com/80782611/185967559-087819b1-3d70-4fb5-87cb-fe1e26f729ea.png)

Please note:
- The subclass tree is represented with purple dashed arrows and boxes (around all classes for which the isSubClassOf-relation applies) in the graph.
- The subproperty relations are not represented in the graph, only mentionened in the text
- Brand is removed, as I would not consider this to be a subclass of EditorialObject
- Motto is introduced as a grouping mechanism for all sorts of different EditorialObjects
- Article and Post (or Posting) are introduced to represent online and social media content. More subclasses might be useful.
- BMContent is an application specific class that imho should rather be left out from the EBUCore+ standard and be moved to a FIMS application standard
- Item and Clip might be equivalent

**Comment by kimviljanen** [comment]
Some random thougts:
- I am not sure that EditorialSegment would also be an instance of EditorialWork, because for example Shots or Clips require often work by Editorial people...
- EditorialGroup sounds good… but on the otherhand, creating a Series takes often a lot of Editorial effort, and in that sense an EditorialGroup such as a Series is an outcome of EditorialWork… 
- serial vs series. Do we need both, or would series be enough? Some sources define serial as a mini-series. Is that the intended meaning? 
- Motto - what is the idea or example of this?
- Clips are difficult. We made quite recently a list of all kinds of clips and clip cases at Yle. It is a broad term…
- Articles can also form series. E.g. an Article series on Brexit.
- Shot/Take/Scene/Clip … I feel that there are quite many arrows going on in the picture in this area. Are we sure about all of the relations (arrows)? E.g. Is scene and Scene always/sometimes/ever required between a shot and a clip?
- There surely are a lot of other types of EditorialWorks too than only Programs, Articles and Posts… At least from Yle’s perspective, I would propose we would only have Programs and Articles, I feel that Post is not that core to the business… (am I getting old fashioned?) … or alternatively we end up adding a lot of other types of EditorialWorks too such as Concerts, Live events, Exhibitions, Magazine publishing, what not.

**Comment by JuergenGrupp** [comment]
I edited my first comment to explain better about the terms "work" and "segment" and to make the proposed hierarchy of subclasses of EditorialObject more visible. Some additional comments on Kim's feedback (Thank you!) will follow soon.

**Comment by JuergenGrupp** [comment]
My answers to Kim's thoughts:
> I am not sure that EditorialSegment would also be an instance of EditorialWork, because for example Shots or Clips require often work by Editorial people...

EditorialSegment is not a subclass of EditorialWork, but of EditorialObject. EditorialWork is also a subclass of EditorialObject. An EditorialWork describes a piece of content that is intended to be published and consumed as a whole, because it tells one story or combines fragments into a common publishing format. Typical examples are: a movie, a documentary, a news show. (Naming: the noun “work” has many meanings, one of them being “something produced or accomplished by effort, exertion, or exercise of skill”. Other naming candidates might be “piece”, “body”, …).  EditorialFragments are usually published and consumed as parts of an EditorialWork. E.g. a news item is published within a daily linear news show, or as a web Article, which is the combination of a picture, a headline, some teaser text, and the video/audio file. Only that combination makes it publishable and consumable as a piece.

> EditorialGroup sounds good… but on the otherhand, creating a Series often takes a lot of editorial effort, and in that sense an EditorialGroup such as a Series is an outcome of EditorialWork…

That is exactly why EditorialGroup is a subclass of EditorialObject (not “an outcome of EditorialWork”), that can group all other subtypes, even other EditorialGroups.

> serial vs series. Do we need both, or would series be enough? Some sources define serial as a mini-series. Is that the intended meaning?

Following Merriam-Webster dictionary, a "serial" is “a work appearing (as in a magazine or on television) in parts at intervals”. So, it’s typically one story chopped into parts and published as episodes that you can't miss to follow the whole story, while a "series" typically  does not have a single story, but is formed into a group because of the common format or publication pattern of its part (M-W: “a set of regularly presented television programs each of which is complete in itself”). I think this distinction is really valuable, e.g. when applying business logic for selecting the display title in an on demand service offering.

> Motto - what is the idea or example of this?

It's a grouping mechanism for parts or pieces of totally different types. E.g. Twice a year ARD publishes audio/video/text content on all platforms in the format of movies, documentaries, news, talk-shows, articles, ... all compiled to fit to a motto like "Cancer", "Kids", "Working life in the 21st century", "Democracies under pressure"

> Clips are difficult. We made quite recently a list of all kinds of clips and clip cases at Yle. It is a broad term…

I see. If we can't find a sharp and understandable definition and a good reason for it to be there, it should not be part of the standard. My intention was to accompany the use of the term "item", which to me sounds very news related, while clip could represent audios or videos typically used online and in social media. Interested to hear more opinions on that ...

> Articles can also form series. E.g. an Article series on Brexit.

Agreed. The graph needs an update. 

> Shot/Take/Scene/Clip … I feel that there are quite many arrows going on in the picture in this area. Are we sure about all of the relations (arrows)? E.g. Is scene and Scene always/sometimes/ever required between a shot and a clip?

All of the arrows between these Classes represent sub-properties of "hasParentEditorialObject". Maybe I missed some of them. This depends largely on what we really mean with the above terms. Interested to discuss this ... 

> There surely are a lot of other types of EditorialWorks too than only Programs, Articles and Posts… At least from Yle’s perspective, I would propose we would only have Programs and Articles, I feel that Post is not that core to the business… (am I getting old fashioned?) … or alternatively we end up adding a lot of other types of EditorialWorks too such as Concerts, Live events, Exhibitions, Magazine publishing, what not.

That is exactly the intention of those subclasses. We could add all those that we consider helpful and generic enough to be part of the standard. Anyone applying the standard can also add own classes as siblings or as children. But then we will sacrifice some benefit for inter-organisational exchange of data, e.g. a PSM offering data over a public API to serve an open data initiative. That's why I think, we will never be complete here, but we should nevertheless include those classes that we consider helpful and generic. E.g we have already included Scene, Shot and Take into CCDM, even if we do not really represent online articles in CCDM.

**Comment by kimviljanen** [comment]
Thanks, Jürgen! My original post seem to be missing a few essential words here and there which changed my intended meaning. But your answers anyway helped to understand the proposal better.

One missing word was in my comment on the Editorial Work. So I was thinking that A Series can also be a form of Editorial Work. Perhaps a Serial is a good example on content which is intended to be consumed as a whole, and hence it is a sort of an instance of Editorial Work.

Defining EditorialWork as something that is intended to be published and consumed as a whole might be sometimes slightly difficult, because in many cases the same content is intended both to be published as a whole and at the same time as source material for other versions of the same content. For example, the live broadcast of a football game is intended to be watched live as it is, but the catchup version might be cutted shorter (cutting out all non essential parts such as waiting for the game to start) and also clips may be produced to be consumed as part of the text article version of the coverage of the game. Years later the archive might publish national highlights or highlights of individual persons careers - which are new versions again of the same source material… so basically there might be one intended Work intended for publishing and consuming as a whole (e.g. scripted drama), but in practice there are cases where the distinctions are not that clear such as in sport, news, live events, archive publishing, ….

Serial - OK by me. Just pointing out that at our company we technically only have series and singles - we do not separate serials from series (but it is something we should perhaps consider).

Motto - OK. Sounds good. Just as additional information without proposing any change: At Yle we have called entities that are used for somewhat similar grouping purposes with many names (in diffent systems, implementations and data models etc), such as ”Product” or ”Product Family”, ”Yle Wholes” (not sure if the translation makes sense), ”Events”, in some use cases also ”Packages”, ”Editorial sections”, … What you described (e.g. Cancer) could be in our systems considered for example as an Yle Whole…

**Comment by tormodv** [comment]
**This is very good!**
Thanks, both of you.

I have a few points that I like to highlight.

**Item**
As part of a programme, an item is an EditorialSegment, but it can at the same time represent a complete intellectual work, e.g. a piece of music. The item is a segment of the programme and is an extract of some other EditorialObject, representing the original. I think this needs an explanation in the documentation.   The other EditorialSegments do not have the same duality. By the way we already have http://www.ebu.ch/metadata/ontologies/ebuccdm#isExtractOf which is important when describing the items in a programme.

**Motto**
_Draco dormiens nunquam titillandus_
The motto of Hogwarts School of Witchcraft and Wizardry, which translates to “Never tickle a sleeping dragon” 
I like the concept that ARD attributes this word to, but the common meaning of a motto is more like it is used at Hogwarts or in operas where it translate to the german concept of Leitmotiv, ref [https://de.wikipedia.org/wiki/Leitmotiv](url)

I have heard brand or campaign be used for describing the concept you are calling motto.

**Many kinds of programmes**
I think it will not be a problem if people either make subclasses of programme or EditorialWork

**Gruops of programmes**
We cover this well in the proposal.

I remember from my radio days we also sometimes had a grouping of items. This can be described using the timeline on the item, to add more items, but should we for this use the name itemgroup?

**Comment by alexandre-rouxel** [comment]
Don't you think  "theme" can be used instead of "motto" considering this definition 
https://wikidiff.com/theme/motto

**Comment by tormodv** [comment]
> Don't you think "theme" can be used instead of "motto" considering this definition
> https://wikidiff.com/theme/motto

I like the word theme much better in this context.

**Comment by tormodv** [comment]
**Part**

We have a few object properties using the class Part. But Part are almost described as a segment. Can we just move the properties to target the Editorial Segment instead? " isPartOf" and "hasPart" is much used properties, not only in EBU Core.

**Comment by tormodv** [comment]
For relationship EditorialWork/EditorialObject to EditorialGroup i propose we reuse hasMember/isMemberOf

**Comment by JuergenGrupp** [comment]
Thank you all for your feedback. I agree to most of them and have sketched a new graph. Find some more explanations below the graph.
![image](https://user-images.githubusercontent.com/80782611/190219913-d3265888-c174-48e6-a1dd-035682754a1f.png)

Highlights:
- More focus and clarity was put onto the properties: sub-property relations were introduced. This simplifies adding more sub-classes of EditorialObject as they inherit the 3-layer isMemberOf structure while still allowing to add properties that narrow down to "has[name of class pointed to]". Do you think they should be part of the standard at all? Please comment!
- Please note that only the most important object properties are depicted, especially on the right half. More properties may be defined (or even inferred, eg a Shot may also be linked to a Programme, if a Scene or an Item connects the two). 
- EditorialGroups/EditorialWork/EditorialSegment all can have "isMemberOf" and its sub-properties to instances of the same classes (i.e. same hierarchy level). This decouples the need for classification from the need for grouping. 
- hasRelatedEditorialObjects is imho a property that needs further sub-properties to narrow the relation between EditorialObjects on the same level (Group, Work, Segment). Should we provide some of them? We probably have already some (eg "isVersionOf"), do we? Please comment! 
- EditorialGroup is strictly used for grouping EditorialObjects
- EditorialSegment is strictly used for EditorialObjects that do not tell a whole or at least a significant part of a story, but usually serve as building blocks for other stories.
- Item is now a subclass of EditorialWork (its duality, as Tormod wrote, is better described there than as subclass of EditorialSegment)
- Part can be replaced by EditorialSegment (agree with Tormod)
- Clip is removed (agree with Kim)
- Trailer and MakingOf is added as EditorialWork (At SWR we have currently a use case requiring these concepts)
- Motto is now Theme (agree to all)
- The class "..." symbolizes extensibility

**Comment by kimviljanen** [comment]
Good work! One comment: 

If I understand correctly, you propose to create classes Trailer and MakingOf. To me they sound too specific and slightly random to be part of the standard. I think they are a genre or ”type” (not in the RDF but Dublin Core sense) of an content object (EditorialObject). The genres/types would probably be managed in a controlled vocabulary of some sort.

There needs to be properties to declare the required relations between EditorialObjects. Do we have a mechanism for all following cases?

Examples: 
1. EditorialObject (genre: trailer) X _advertises_ EditorialObject (genre: Wester Movie) Y.
2. EditorialObject (genre: MakingOf Documentary) Z _isAbout_ Y.
3. EditorialObject (genre: Review) R _reviews_ Y.

**Comment by JuergenGrupp** [comment]
Thank you for your questions, Kim!

> If I understand correctly, you propose to create classes Trailer and MakingOf. To me they sound too specific and slightly random to be part of the standard. I think they are a genre or ”type” (not in the RDF but Dublin Core sense) of an content object (EditorialObject). The genres/types would probably be managed in a controlled vocabulary of some sort.

I generally see two options, when refining a class: typifying (eg by using a "type"-attribute with the data type "skos:Concept") or subclassing (eg Trailer as sub-class of EditorialWork). I prefer typifying, if all data and object properties of the two types are required and used in the same way. I prefer subclassing, if the data or object (!) properties of the two classes have significant differences. More criteria are: which way is easier to introduce new types or new classes and which way supports easy use of SPARQL. The decision is hardly ever black or white, especially here, both ways are possible and have pros and cons. My reasons to prefer classes over types in this case are:

- the model is easier to understand, because the terms are well known and we can sketch it as shown above
- we have already started to create separate sub-classes of EditorialWork to distinguish programmes, items, articles, posts ... (probably because of the first reason mentioned above). If we would switch to types, we would end up in only having the three classes EditorialGroup/-Work/-Segment, with the use of many object properties being dependent on the specific type (Programmes can have Items, but Trailers cannot).
- it's easy to define new subclasses if needed for an application using EBU Core+. These classes can be well described, especially with their object properties and then, if needed, requested to become part of the standard. It would be easier for the Editorial Committe to understand all implications of the new class as of a new value of skos:Concept.
- SPARQL queries involving these classes are easier to write, read and maintain 

> There needs to be properties to declare the required relations between EditorialObjects. Do we have a mechanism for all following cases?
> Examples:
>
> - EditorialObject (genre: trailer) X advertises EditorialObject (genre: Wester Movie) Y.
> - EditorialObject (genre: MakingOf Documentary) Z isAbout Y.
> - EditorialObject (genre: Review) R reviews Y.

I think the examples allow to compare nicely with my arguments from above:

- Trailer X --hasProgramme-->Programme (genre: Western Movie) Y  (a trailer always is there to advertise or promote a larger piece of content)
- MakingOf Z --hasProgramme--> Programme Y (a making-of is always about some piece of content)
- Review R --hasProgramme--> Programme Y (a review is always a review about some piece of content)
- (even: Review R --hasSeries--> Series S (could represent a review about a complete series)

**Comment by saerdnaer** [comment]
I think you still need a grouping for `Serials` (which probably the reason why `Brand` exists) – for example think about 'bucket' for the three series [Anna und die wilden Tiere](https://de.wikipedia.org/wiki/Anna_und_die_wilden_Tiere ), [Pia und die wilden Tiere](https://de.wikipedia.org/wiki/Pia_und_die_wilden_Tiere) & [Paula und die wilden Tiere](https://de.wikipedia.org/wiki/Paula_und_die_wilden_Tiere)

**Comment by JuergenGrupp** [comment]
> I think you still need a grouping for `Serials` (which probably the reason why `Brand` exists) – for example think about a 'bucket' for the three series [Anna und die wilden Tiere](https://de.wikipedia.org/wiki/Anna_und_die_wilden_Tiere), [Pia und die wilden Tiere](https://de.wikipedia.org/wiki/Pia_und_die_wilden_Tiere) & [Paula und die wilden Tiere](https://de.wikipedia.org/wiki/Paula_und_die_wilden_Tiere) (and few other spin-offs…)

That's an interesting example and I would propose three possible solutions within the existing model:
1) A `Serial` is a subclass of EditorialGroup and thus can be member of another EditorialGroup. The three `Serials` mentioned above could be members of another `Serial` named "Die wilden Tiere". I would recommend this, if the latter is described best with the typical attributes of an EditorialObject, like author, titel, genre, description, ...
2) The three `Serials` mentioned above could be published under a `Brand` named "Die wilden Tiere". I would recommend this, if the `Brand` is used not only as "bucket" for the `Serials`, but also for other offerings like podcasts, events, a website, a set of online games (or even mugs, caps, umbrellas) ...
3) Both cases might apply. Just because an `EditorialObject` and a `Brand` have the same name does not mean they are the same thing.  Eg. "Tageschau" is the name of a `Series` and also the name of a `Brand`.

**Comment by JuergenGrupp** [comment]
I have prettyfied and extended the figure on EditorialObjects. See explanations below.

![image](https://user-images.githubusercontent.com/80782611/192013551-285955bd-c748-409d-bcf8-232c2a0e22f0.png)

Explanations:
- I have added subclasses of EditorialWork: OnePiecer, Episode, Outtakes, Bonus, Promotion, Reminder
  - OnePiecer: a piece of work that usually does not contain Items and is not part of a Serial or Series. e.g. a regular movie
  - Episode: a piece of work that usually does not contain Items and is part of a Serial or Series. e.g. a podcast
  - Outtakes and Bonus are "additional" EditorialWorks that only exist because of the EditorialObject they refer to. They serve the purpose of "adding something" that is expressed by their name (also applies to Trailer and MakingOf)
  - Promotion is an EditorialWork that has a marketing function for a commercial product or service
  - Reminder is an EditorialWork that refers to a Promotion by reminding the user of the promoted product or service in the Promotion consumed earlier
- I have added one subclass of EditorialGroup: CampaignPackage, which groups a set of Promotions along with Reminders. This is the structure of a package of commercials delivered from sales houses to broadcasters. About the name: Campaign is already taken by a class from the Planning domain, describing a set of commercials, a target audience, a target resonance, and a set of PublicationEvents. So, a Campaign could refer to a CampaignPackage to describe the set of commercials. 
- To reduce the number of arrows in the graph, I have sketched a few boxes with dotted lines that only serve the purpose of allowing to use less arrows.
- I have only sketched arrows that are subclasses of either isMemberOf or hasRelatedEditorialObject. I have omitted the names, but would propose to name them according to the pattern „has[name of class pointed to]“.
- Inverse relations can be added where appropriate and useful.
- I tried to add only classes, that are applicable both to audio and video. 
- Every class has a specific structural role that distinguishes it from others. Therefore, they are worth to be modelled and deserve a node in the hierarchy of EditorialObjects. Sometimes this may be difficult to see, when you only read their names, because names are not as precise as the definition of the class and its relations. In these cases the graph will help to "tell the story".

**Comment by saerdnaer** [comment]
@JuergenGrupp What is the difference between `Programme` and `Episode`? 
Is https://www.br.de/mediathek/podcast/das-computermagazin/eugh-urteil-emoji-geburtstag-denunzieren-in-saudiarabien-internet-im-us-reservat/1868480 (a podcast episode consisting of four items) both?

**Comment by JuergenGrupp** [comment]
Thank you for the questions, @saerdnaer !  
> What is the difference between `Programme` and `Episode`?

An `Episode` does not encompass `Item` , a `Programme` can. In this sense `Episode` is only narrowing the meaning of `Programme` but is not different from a structural point of  view. We included it in the model to foster understanding of the model in the world of serials and series. Your example could only be modelled as `Programme`, although in your business context you would name it an episode. That's a really good indication to rethink the use of `Episode`. We'll consider that.

> Is there a better name for OnePiecer? Why not call it Movie or Single?

We have discussed the "OnePiecer" and will not include it in the standard, for almost the same reason as above: a `Programme` can do anything a "OnePiecer" can.

**Comment by JuergenGrupp** [comment]
Sorry, @tormodv, for reopening this long issue again! I felt that the little change I am proposíng here is easier to understand in the context of this thread than in a new one. And I think that the proposal will end up in only very little code changes. Here we go:

Again, a simpler and prettified graphic of the hierarchy. See comments on changes below.
![image](https://user-images.githubusercontent.com/80782611/194598998-fe54a520-a0c0-40a0-9bbe-ce8e0f16779c.png)

- The `onePiecer` is removed, as already stated in my last comment
- Also the `Episode` is obsolete. I assumed earlier that `Episode` can be part of a `Serial`, but not a `Series`. But according to Merriam-Webster Dictionary an `Episode` can be part of either one. If it is part of a `Series`, it typically contains `Item`s. This is exactly the example that @saerdnaer has provided. Therefore it can have the same object properties as a `Programme` and does not need to exist as class in the model.
- These two changes allowed to sketch a new graphic with fewer arrows, hence the update here.
