### ISSUE TITLE
Do we need personName

### ISSUE THREAD

**Issue by tormodv** [ebu/ccdm#215]
Ref : http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#personName

Do we need personName? 
This is a property of the Person class, but as with all classes, this already has a name field in addition to the the givenName and familyName properties.

Can we remove it?

**Comment by JuergenGrupp** [comment]
I think personName is obsolete and we should remove it. If there is not a good reason for two properties covering the same information, one property is enough.
Are there more xyzName properties to be removed?
