### ISSUE TITLE
How to represent a user journey?

### ISSUE THREAD

**Issue by JuergenGrupp** [ebu/ccdm#220]
A user journey is a sequence of consumptions of a user. A dataset representing this would answer the questions "What content was consumed before?" and "What content is consumed after?".  I came across these two questions when I was talking to our audience research department lately.

Speaking in terms of EBU Core+, we could use a **daisy chain** of **ConsumptionEvents**. There is a property "hasRelatedConsumptionEvent" pointing from one ConsumptionEvent to another. The relation is not really specified, so I am in doubt whether we should include a property like "isFollowing" pointing from a ConsumptionEvent to the preceding ConsumptionEvent. Should "isFollowing" replace "hasRelatedConsumptionEvent"? Or should it be a sub-property instead? Or should it even be a property that is more general, not limited to ConsumptionEvents, but for all "Events"? Something like "Event" "isFollowing" "Event"?
Comments welcome!

**Comment by tormodv** [comment]
We have already introduced the use of SKOS, mostly in the sense of skos:Consept.

Skos also defines semantic relations, and xkos, an extension, takes this further. 

<img width="268" alt="Skjermbilde 2022-11-18 kl  15 26 02" src="https://user-images.githubusercontent.com/12021922/202730775-6e290880-d8e0-4bc7-9b92-724b2efc49fa.png">


At the end you have a few sequential relationships, can we use those?

**Comment by JuergenGrupp** [comment]
Looks good to me! 

- xkos:precedes and xkos:succeeds are perfect for directly connected ConsumptionEvents.

- xkos:after and xkos:before might even be used for ConsumptionEvents in user journeys that are not directly connected, eg. if the user has taken a "detour" on his journey, consuming some content of other publisher's PublicationEvents, that we might not have a record of.

**Comment by alexandre-rouxel** [comment]
What about consumption Events in parallel?   As an example, 1 user with 2 devices can consume 2 ConsumptionEvents at the same time. This happens more and more often.

**Comment by tormodv** [comment]
I guess further up in the list, we have primarily semantic relations, like "mammal" is a broader term than "cat".

But the three under xkos:sequential seem like a good addition to EBU-core.

**Comment by JuergenGrupp** [comment]
> What about consumption Events in parallel? As an example, 1 user with 2 devices can consume 2 ConsumptionEvents at the same time. This happens more and more often.

If we compare only the start times, then there is always a possibility to distinguish the two events, even if they overlap while their duration. We can calculate the **sequence** of a list of ConsumptionEvents of a single user, no matter what the platform, channel or consumed content is. Also, the duration of the ConsumptionEvent is not decisive. A user journey is not neccessarily a daisy chain (one event ending before the next is starting), it can also be an timewise overlapping collection (events can be parallel) or even with gaps on the timeline.
