### ISSUE TITLE
Linking PublicationChannel and Platform to classes from the domain Consumption

### ISSUE THREAD

**Issue by JuergenGrupp** [ebu/ccdm#222]
In the current model I cannot describe the links between a Platform or its PublicationChannels to classes like ConsumptionDeviceProfile, ConsumptionDevice and Consumer. Neither EBUCore nor CCDM provided sufficient modelling here. So, here's the current modelling situation:
![image](https://user-images.githubusercontent.com/80782611/200835410-27dbf105-51cf-4994-b856-a7fa737c014f.png)

For some of the concepts, I am not sure, what the benefit is and whether we need them at all (see orange marked elements and question):

![image](https://user-images.githubusercontent.com/80782611/200835785-b1802f98-5ad3-4661-b450-0891fef05dac.png)

Therefore, I propose to remove some of them and, more importantly, introduce some more links between the exisiting concepts (see red marked elements and hints):

![image](https://user-images.githubusercontent.com/80782611/200836716-732a6ada-2b46-4a97-bcda-3a3515900a65.png)

Looking forward to your comments!

**Comment by JuergenGrupp** [comment]
I am not sure, whether you @tormodv, @alexandre-rouxel and @kimviljanen have already noticed this issue. I am looking forward to your comments!

**Comment by tormodv** [comment]
Looks good, I'll write a change that we can have a look at.

**Comment by tormodv** [comment]
<img width="859" alt="Skjermbilde 2022-11-19 kl  22 49 51" src="https://user-images.githubusercontent.com/12021922/202873176-853e68fd-8380-4f13-a234-b830d4479ef0.png">

I will propose to keep the service. In English, Channels and platforms are often referred to as services, and the class will act as a superclass for the common properties of Channel and Platform.

I'm not sure that we need the rename the "compliesWith", together with the existing "Supports Consumption DeviceProfile" the classes are connected. 
The device complies with some demands for capabilities required by the service/platform/cannel.

We can of course add the relations in red if we need.

What du you think?

**Comment by alexandre-rouxel** [comment]
I agree: a target platform is a platform, and the relation hasTarget Platform: does the job
About ConsumptionDevice: @JuergenGrupp. A  ConsumptionDevice is linked with a Consumer who consumes a Service, a Platform, or a publishing Channel. I don't see the connection in your diagram.
We should discuss if we want to keep the class service. If no then we can discuss the changes.

**Comment by JuergenGrupp** [comment]
When I tried to paint the graphic with the result of our last discussion, I stumbled over the "Service" again: 

In linear publication, a **Service** might describe the users perception, whereas the **PublicationChannel** better describes the technical sides of the publication, given by the platform. E.g. SWR's linear TV service is called "SWR Fernsehen" and it is published through different publication channels (defined e.g. by frequency range, Codec, etc) on different platforms (DVB-S, DVB-T), which, from the consumer perspective might also be numbered ("Channel 1") or named ("SWR Fernsehen"). Hence, to represent this, it would be good to keep the class **Service**. However, not as a superclass, but as an additional class, related to **PublicationEvent**, **PublicationChannel** and **Platform**. (Maybe even to **ConsumptionDeviceProfile**?).

This modelling also allows to omit an object of class **Service** completely, when describing a non-linear publication, e.g. a **PublicationEvent** on the **Platform** "Youtube" in the **PublicationChannel** "SWR".

That's my updated proposal:
![image](https://user-images.githubusercontent.com/80782611/205666472-e1990275-a52b-42ce-bca3-4786705f685b.png)

**Comment by JuergenGrupp** [comment]
The Editorial Committee agreed to this proposal and additionally to change the names to "PublicationService" and to "PublicationPlatform".
The examples for linear and non-linear uses of this model should be part of the documentation later on.
