### ISSUE TITLE
Use of datatype xsd:date

### ISSUE THREAD

**Issue by tormodv** [ebu/ccdm#4]
Not all datatypes are first-class citizens in every triplestore. xsdDatetime has more support than xsd:date. A SPARQL endpoint can do the math on DateTimes, but very often not on Dates.

Should we go for only using date-times?

**Comment by JuergenGrupp** [comment]
I support to replace xsd:date. Would xsd:dateTime or xsd:dateTimeStamp be better?

**Comment by tormodv** [comment]
Make the change
