### ISSUE TITLE
Renaming of generic properties?

### ISSUE THREAD

**Issue by tormodv** [ebu/ccdm#42]
In #41 i used :hasType some skos:Consept for every kind of type/genre. For the generic name, I used objectName, is just name better?
"description" instead of objectDescription?

"identifier" instead of objectIdentifier?

**Comment by kimviljanen** [comment]
Generic labels for properties is better: name, description, identifier.

**Comment by JuergenGrupp** [comment]
Editorial committee: Tormods proposal is accepted.

**Comment by tormodv** [comment]
Ups, we have the class :Identifier, perhaps is it best to keep the name of the property to hasIdentifier?
