### ISSUE TITLE
Do we need BBCconcepts?

### ISSUE THREAD

**Issue by tormodv** [ebu/ccdm#54]
This is just here for reference.

Same situation as FOAF, which we removed.

**Comment by alexandre-rouxel** [comment]
We discuss this topic at our next meeting: Tuesday 15 Feb
pro and cons

**Comment by alexander-schulze** [comment]
From the technical perspective, I see a few statements like BBC’s “Place” being equal to EBU’s ”Location”, which is few knowledge but it’s knowledge, which might be useful. Do we know users/consumers that make use of this particular knowledge? If not, we could remove it completely. If yes, we could think of independent mapping ontologies as a general concept. This would keep the EBU CCDM ontology concise and clean, but would still enable us to provide this “equality knowledge” to someone who really works with it. In general, combining ontologies always is easy, this is one of the paradigms of the semantic web. Usually, splitting merged ontologies is more difficult.

I would not merge the BBC ontology and the EBU Ontology, but provide them separately in a package, if desired by the consumers, optionally with an additional mapping ontology. This enables us to easily maintain them individually and combine them where needed.
