### ISSUE TITLE
:dateBroadcast

### ISSUE THREAD

**Issue by tormodv** [ebu/ccdm#55]
dateFirstBroadcast

**Comment by alexandre-rouxel** [comment]
To be discussed

**Comment by kimviljanen** [comment]
Date first broadcasted sounds correct, but I would point out that date first published online is sometimes also relevant. I think the better way would be to omit the property and use the publication events for identifying the ”firsts”.

**Comment by tormodv** [comment]
The **publication event will ensure that we know when and where**. Date first broadcast feels like it comes from the days when you had one radio channel and one television channel.
