### ISSUE TITLE
Use OWL Time Ontology as inspiration?

### ISSUE THREAD

**Issue by kimviljanen** [ebu/ccdm#56]
Perhaps CCDM’s time related parts would benefit of using https://www.w3.org/TR/owl-time/ as inspiration or as a reference?

**Comment by alexandre-rouxel** [comment]
[CCDM dates.pdf](https://github.com/ebu/ccdm/files/8050705/CCDM.dates.pdf)
Should be clarified. We wanted to add the notion of reliability for the intervals
