### ISSUE TITLE
:Episode and :Season do not have an index or order?

### ISSUE THREAD

**Issue by alexander-schulze** [ebu/ccdm#70]
To my perception, episodes as well as series are often published with "[Name], Season [S], Episode [E]".
I'm wondering if in addition to the date time information, also an explicit "number" or "index" should be maintained.
Maintaining that in the titel could become difficult in case the orders change.

**Comment by kimviljanen** [comment]
I support the idea that the title should not contain extra metadata such as episode numbers or age restictions or anyhing else than the title only.

A side note: The episode numbering can sometimes be a tricky topic, but probably most robust approach is to have a property for the episode number, as you propose. Season numbering is probably best handled by linking episodes to a season object, and then the season object has a episode number.

Tricky details:
- in some cases a broadcaster might not own the publisihing rights to all episodes in a series or season
- in some cases broadcaster might decide not to show one episode (e.g. if one episode in a childrens series is considered to be too violent) … and then the question rises: should there be a break in the episode numbers or not. (Of course I would recommend using the original episode numbering and not be considered about the missing episode number.)
- not all series use episode numbers, e.g. Evening news series typically is ordered e.g. by date.
- in some cases the episode number should be running independently of the seasons… that is if there are 10 seasons with 20 episodes, the episode three in season three would get number 43.
- in some cases season numbers are not used, but the year should be used. E.g. in current affairs type of series.
- …

Many of these cases are quite easy to solve, but all of them are things that have been discussed in length at least in our broadcasting company during the years.

**Comment by alexander-schulze** [comment]
On the same page with you. Thanks for exposing the use cases and their details.
From the modelling perspective, this leads me to the conclusion that we should ...

1. introduce an optional "seasonNo" as a string property for seasons
2. introduce an optional episode-no as a string property for episodes
3. infer the "seasonNo" of an episode by their reference/relation, like you recommend
4. using "string" as data type would keep us open for any kind of numeric or alphanumeric ordering (in addition to the date and time and by simply converting a string to number in a select where needed)
5. declaring the "seasonNo" and "episodeNo" optional (i.e. max 1) would not make it mandatory to provide them, but we can put some QA on top where needed.
6. the above relates to the _original_ version. Mapping to third parties should be done by the third party, where needed. As far as I understood, the CCDM is meant to be extended like required by a consumer, so the consumer (or even we if we wanted) could easily add a field "customSeasonNo" or "customEpisodeNo".

**Comment by alexander-schulze** [comment]
In general, first of all the **model** should keep us **open for options**. The **contents** can be managed and quality controlled by processes on top of it.

**Comment by tormodv** [comment]
We have attributes for this: episodeNumber, episodeNumberInSeason and episodeNumberInSeries that was meant to cover this.
They have domain Episode, I think in due time they should perhaps be added as Class restrictions as well.

**Comment by tormodv** [comment]
We also have the attribute seasonNumber

**Comment by alexander-schulze** [comment]
> We have attributes for this: episodeNumber, episodeNumberInSeason and episodeNumberInSeries that was meant to cover this. They have domain Episode, I think in due time they should perhaps be added as Class restrictions as well.

I agree.
