### ISSUE TITLE
:Episode always has parts?

### ISSUE THREAD

**Issue by alexander-schulze** [ebu/ccdm#71]
In version 2.3.0 as of 2022-03-03, I notice the property :hasPart for Episode being modelled with some :Part, which implies that each episode at least needs to have one part. Is this the case, i.e. is that mandatory? If not, we should model that using "only".

**Comment by tormodv** [comment]
It's not mandatory. Will substituting with only fix this?

**Comment by alexander-schulze** [comment]
"some" means "one or more", but one would be mandatory
"exactly 1" means exactly one mandatory
"only" means optionally one or multiple ones
"max 1" means 1 optional but not mor than 1, actually one optional

Here some Protege Manchester Syntax documentation: ([some only max in manchester syntax](http://protegeproject.github.io/protege/class-expression-syntax/))

**Comment by tormodv** [comment]
After a look at the model, we have a few "some" that should have been only. The use cases of CCDM is diverse so mandatory will often backfire.
I'll write a fix ASAP
