### ISSUE TITLE
Groups of EditorialObjects to be represented by subclasses of EditorialObjects

### ISSUE THREAD

**Issue by JuergenGrupp** [ebu/ccdm#84]
The CCDM group has decided to represent groups of EditorialObjects like a "series", a "season", etc. as subclasses of EditorialObjects. Grouping is then represented by "hasMember" / "isMemberOf" relations.

**Comment by tormodv** [comment]
If we are happy with the current class tree, which is a variant of the proposal above, we can close this issue.

**Comment by JuergenGrupp** [comment]
Currently, Groups are not subclasses of EditorialObjects but of BusinessObjects. BusinessObjects have many properties that I would rather see in EditorialObjects. I doubt the need for the class BusinessObjects in general. What is the benefit? We don't need it as super-class for a Group class, because grouping should be represented by "hasMember"-relations (see above). Do we need it for the BibliograpicalObject? Are we really using this in the audio-visual media industry?

**Comment by JuergenGrupp** [comment]
This issue seems to be resolved through #176.
